# Projeto 01 — Automação e Análise de Dados de Vendas

## 1. Contextualização do negócio

Este projeto simula o cenário de uma empresa varejista que realiza vendas por diferentes canais, comercializa diversos produtos e conta com vendedores distribuídos por regiões.

Os dados comerciais estão armazenados em arquivos separados. Para apoiar a gestão, é necessário consolidar essas informações, avaliar sua qualidade e transformá-las em indicadores que permitam acompanhar o desempenho comercial.

## 2. Problema de negócio

A gestão precisa compreender o desempenho das vendas, identificar os produtos, canais, vendedores e regiões com maior contribuição para os resultados e avaliar o impacto dos descontos sobre a receita.

Entretanto, antes de gerar indicadores confiáveis, é necessário verificar a qualidade dos dados, padronizar informações inconsistentes e estabelecer regras claras para os cálculos.

**Problema central:** como automatizar a consolidação dos dados de vendas e identificar os principais fatores que influenciam o desempenho comercial da empresa?

## 3. Objetivos

### 3.1. Objetivo geral

Desenvolver uma solução em Python para carregar, validar, tratar e consolidar dados de vendas, produtos e vendedores, calcular indicadores comerciais e gerar um relatório gerencial automatizado.

### 3.2. Objetivos específicos

- Avaliar a qualidade e a consistência dos dados.
- Identificar e documentar problemas nos arquivos de origem.
- Definir regras de tratamento e padronização.
- Integrar as informações comerciais em uma base analítica.
- Calcular indicadores de desempenho comercial.
- Identificar tendências e oportunidades de melhoria.
- Automatizar a geração de resultados para apoiar a tomada de decisão.

## 4. Perguntas de negócio

1. Como o faturamento evoluiu ao longo do período analisado?
2. Quais produtos e categorias geraram maior receita?
3. Quais canais de venda apresentaram melhor desempenho?
4. Quais vendedores obtiveram os melhores resultados?
5. Quais regiões concentraram o maior volume de vendas?
6. Qual foi o impacto dos descontos sobre a receita?
7. Qual é a margem estimada das vendas, considerando os custos dos produtos?

## 5. Escopo e limitações

**Período:** janeiro a dezembro de 2025.

**Fontes de dados:**
- `vendas.csv`
- `produtos.csv`
- `vendedores.csv`

**Atividades incluídas:**
- Inspeção e validação dos dados.
- Análise da qualidade das informações.
- Tratamento e integração das tabelas.
- Cálculo de indicadores comerciais.
- Análise exploratória dos resultados.
- Elaboração de conclusões e recomendações gerenciais.
- Geração automatizada de relatório.

**Limitações:** os dados são simulados para fins educacionais e de portfólio. Não serão desenvolvidos modelos preditivos, algoritmos de machine learning ou integrações com sistemas externos nesta versão.

## 6. Abordagem metodológica

O projeto será desenvolvido nas seguintes etapas:

1. Conhecimento e inspeção dos dados.
2. Avaliação da qualidade dos dados.
3. Definição das regras de tratamento.
4. Limpeza e padronização das informações.
5. Integração das tabelas.
6. Definição e cálculo dos indicadores.
7. Análise exploratória e interpretação dos resultados.
8. Elaboração de conclusões e recomendações gerenciais.
9. Automação da geração do relatório.

Cada etapa será documentada antes da implementação, com critérios claros e resultados verificáveis.

## 7. Conhecimento dos dados

Esta etapa tem como objetivo conhecer as fontes de dados disponíveis, identificar sua estrutura e compreender as informações armazenadas em cada arquivo.

Serão analisados três conjuntos de dados:

- **Vendas:** registros das operações comerciais, incluindo datas, produtos, quantidades, preços, descontos, canais e status.
- **Produtos:** cadastro dos produtos, categorias, subcategorias, custos e preços de referência.
- **Vendedores:** cadastro dos vendedores e suas respectivas regiões.

Nesta etapa, os arquivos serão carregados e inspecionados sem alterações. A avaliação de valores ausentes, duplicidades, inconsistências e registros inválidos será realizada posteriormente, em uma etapa específica de qualidade dos dados.

## 8. Inspeção inicial

A inspeção inicial verificará as dimensões dos arquivos, os nomes das colunas, os tipos de dados e uma amostra dos registros.

Essas informações permitirão compreender a estrutura das fontes e preparar as próximas etapas de validação e integração.

In [6]:
# BIBLIOTECAS

from pathlib import Path
import pandas as pd
import numpy as np


# CARREGAMENTO DOS DADOS

## Diretório dos arquivos de dados
diretorio_dados = Path('../dados')

## Carregamento dos arquivos CSV
df_vendas = pd.read_csv(diretorio_dados / 'vendas.csv')
df_produtos = pd.read_csv(diretorio_dados / 'produtos.csv')
df_vendedores = pd.read_csv(diretorio_dados / 'vendedores.csv')

print('ARQUIVOS CARREGADOS COM SUCESSO.')

ARQUIVOS CARREGADOS COM SUCESSO.

In [7]:
# VERIFICANDO AS DIMENSÕES DOS CONJUNTOS DE DADOS

print('DIMENSÕES DOS CONJUNTOS DE DADOS')
print('\b')
print(f'Vendas: {df_vendas.shape[0]} linhas e {df_vendas.shape[1]} colunas')
print(f'Produtos: {df_produtos.shape[0]} linhas e {df_produtos.shape[1]} colunas')
print(f'Vendedores: {df_vendedores.shape[0]} linhas e {df_produtos.shape[1]} colunas')

DIMENSÕES DOS CONJUNTOS DE DADOS

Vendas: 10012 linhas e 10 colunas
Produtos: 20 linhas e 6 colunas
Vendedores: 10 linhas e 6 colunas

In [8]:
# VISUALIZAÇÃO DOS PRIMEIROS REGISTROS DOS CONJUNTOS DE DADOS

display(df_vendas.head())
display(df_produtos.head())
display(df_vendedores.head())

,pedido_id,data_venda,cliente_id,produto_id,vendedor_id,quantidade,preco_unitario,desconto,canal_venda,status
0,PED000001,2025-03-02,CLI00914,PRD019,V010,4,1066.35,0.05,Marketplace,Concluída
1,PED000002,2025-10-04,CLI00211,PRD017,V009,4,855.86,0.00,Loja Física,Concluída
2,PED000003,2025-09-13,CLI01454,PRD018,V002,1,1003.97,0.00,Marketplace,Concluída
3,PED000004,2025-05-10,CLI00935,PRD011,V010,1,2880.72,0.15,E-commerce,Concluída
4,PED000005,2025-01-25,CLI02299,PRD011,V010,4,2888.83,0.00,E-commerce,Concluída

,produto_id,produto,categoria,subcategoria,custo,preco_base
0,PRD001,Notebook Pro 14,Informática,Notebooks,2800,4366.83
1,PRD002,Notebook Essencial 15,Informática,Notebooks,2100,2993.66
2,PRD003,Monitor 24 Full HD,Informática,Monitores,650,1035.74
3,PRD004,Monitor 27 QHD,Informática,Monitores,1050,1605.39
4,PRD005,Teclado Mecânico,Informática,Periféricos,280,360.55

  vendedor_id        vendedor        regiao
0        V001       Ana Souza       Sudeste
1        V002      Bruno Lima       Sudeste
2        V003   Carlos Mendes           Sul
3        V004   Daniela Alves           Sul
4        V005  Eduardo Santos  Centro-Oeste

## 9. Avaliação da qualidade dos dados

Nesta etapa, serão avaliadas a completude, a consistência e a integridade das três fontes de dados.

A análise buscará identificar:

- Valores ausentes.
- Registros duplicados.
- Tipos de dados inadequados.
- Inconsistências de padronização.
- Valores inválidos ou fora dos limites esperados.
- Possíveis problemas nas chaves utilizadas para integrar as tabelas.

Os resultados serão documentados antes da definição das regras de tratamento. Essa abordagem permite preservar a rastreabilidade das decisões e reduzir o risco de distorções nos indicadores comerciais.

In [10]:
# VERIFICAÇÃO DE VALORES AUSENTES

## Quantidade de valores ausentes por coluna
for nome,df in {'VENDAS':df_vendas, 'PRODUTOS':df_produtos, 'VENDEDORES':df_vendedores}.items():
    print(f'\n{nome}')
    print(df.isna().sum())

VENDAS
pedido_id          0
data_venda         0
cliente_id         0
produto_id         0
vendedor_id       10
quantidade         0
preco_unitario     0
desconto          15
canal_venda       10
status             0
dtype: int64

PRODUTOS
produto_id      0
produto         0
categoria       0
subcategoria    0
custo           0
preco_base      0
dtype: int64

VENDEDORES
vendedor_id    0
vendedor       0
regiao         0
dtype: int64

In [11]:
# VERIFICAÇÃO DE DUPLICIDADE

## Quantidade de linhas duplicadas
for nome, df in {'VENDAS':df_vendas, 'PRODUTOS':df_produtos, 'VENDEDORES':df_vendedores}.items():
    print(f'{nome}: {df.duplicated().sum()} linhas duplicadas')

VENDAS: 12 linhas duplicadas
PRODUTOS: 0 linhas duplicadas
VENDEDORES: 0 linhas duplicadas

In [12]:
# VERIFICAÇÃO DOS TIPOS DE DADOS

for nome, df in {'VENDAS':df_vendas, 'PRODUTOS':df_produtos, 'VENDEDORES':df_vendedores}.items():
    print(f'\nESTRUTURA DE {nome}')
    df.info()

ESTRUTURA DE VENDAS
<class 'pandas.DataFrame'>
RangeIndex: 10012 entries, 0 to 10011
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       10012 non-null  str
 1   data_venda      10012 non-null  str
 2   cliente_id      10012 non-null  str
 3   produto_id      10012 non-null  str
 4   vendedor_id     10002 non-null  str
 5   quantidade      10012 non-null  int64
 6   preco_unitario  10012 non-null  float64
 7   desconto        9997 non-null   float64
 8   canal_venda     10002 non-null  str
 9   status          10012 non-null  str
dtypes: float64(2), int64(1), str(7)
memory usage: 782.3 KB

ESTRUTURA DE PRODUTOS
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   produto_id    20 non-null     str
 1   produto       20 non-null     str
 2   categoria     20 non-null     str
 3   subcategoria  20 non-null     str
 4   custo         20 non-null     int64
 5   preco_base    20 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.1 KB

ESTRUTURA DE VENDEDORES
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vendedor_id  10 non-null     str
 1   vendedor     10 non-null     str
 2   regiao       10 non-null     str
dtypes: str(3)
memory usage: 372.0 bytes

### 9.1. Análise dos resultados da qualidade dos dados

Os resultados mostram problemas concentrados na tabela de vendas. As tabelas de produtos e vendedores não apresentam valores ausentes nem linhas duplicadas.

|PROBLEMA|RESULTADO|IMPLICAÇÃO PARA O NEGÓCIO|
|--|--|--|
|Vendedor ausente|10 registros|Dificulta atribuir corretamente as vendas aos vendedores e analisar seu desempenho.|
|Canal de venda ausente|10 registros|Prejudica a comparação entre canais comerciais.|
|Desconto ausente|15 registros|Impede calcular com segurança a receita líquida dessas vendas sem definir uma regra.|
|Linhas duplicadas|12 registros|Pode inflar o faturamento e a quantidade vendida se forem contabilizadas novamente.|
|Datas armazenadas como texto|Todas as vendas|Exige conversão antes de análises temporais.|
|Tipos numéricos|Quantidade, preço, desconto e custos identificados como numéricos|A estrutura básica é adequada, mas ainda precisamos validar os valores e suas regras de negócio.|

**Observação importante:** as 12 linhas duplicadas representam duplicidade integral. Ainda não podemos concluir que todas devam ser excluídas sem examinar os registros e confirmar a regra de identificação de uma venda.
Também não devemos assumir que desconto ausente significa desconto zero. Essa decisão precisa ser justificada pelo significado dos dados.

### 9.2. Verificação de consistência e validade

Além dos valores ausentes e das duplicidades, é necessário verificar se os dados respeitam os critérios esperados para as operações comerciais.

Serão investigados:

- Quantidades iguais a zero ou negativas.
- Descontos fora do intervalo esperado.
- Datas inválidas ou em formatos inconsistentes.
- Variações na padronização de status e categorias.
- Identificadores de produtos e vendedores sem correspondência nos cadastros.
- Possíveis inconsistências entre preços de venda, custos e preços de referência.

Nesta etapa, os problemas serão identificados e quantificados, sem alteração dos dados originais. As regras de tratamento serão definidas após a análise dos resultados.

In [16]:
# VERIFICAÇÃO DE QUANTIDADES IGUAIS A ZERO OU NEGATIVAS
quantidades_invalidas = df_vendas[df_vendas['quantidade'] <=0]
print(f'REGISTROS COM QUANTIDADE ZERO OU NEGATIVA:')
display(quantidades_invalidas)

REGISTROS COM QUANTIDADE ZERO OU NEGATIVA:

,pedido_id,data_venda,cliente_id,produto_id,vendedor_id,quantidade,preco_unitario,desconto,canal_venda,status
1030,PED001031,2025-09-04,CLI02417,PRD008,V005,0,2287.98,0.00,E-commerce,Concluída
1543,PED001544,2025-06-01,CLI00833,PRD020,V009,0,649.22,0.03,Marketplace,Concluída
1650,PED001651,2025-10-09,CLI01167,PRD006,V001,0,206.81,0.08,Loja Física,Devolvida
3630,PED003631,2025-02-22,CLI00796,PRD006,V006,0,200.83,0.05,E-commerce,Concluída
3654,PED003655,2025-05-25,CLI01214,PRD002,V004,0,2984.13,0.00,Loja Física,Concluída
3845,PED003846,2025-06-01,CLI02367,PRD008,V003,0,2279.02,0.00,E-commerce,Concluída
5550,PED005551,2025-01-30,CLI01040,PRD010,V007,0,1611.87,0.10,Marketplace,Concluída
5573,PED005574,2025-05-01,CLI00277,PRD008,V002,0,2336.97,0.00,Marketplace,Concluída

In [20]:
# VERIFICAÇÃO DOS FORMATOS E CONVERSIBILIDADE DAS DATAS

## Exemplos de valores originais
display(df_vendas['data_venda'].drop_duplicates().head(5))

0    2025-03-02
1    2025-10-04
2    2025-09-13
3    2025-05-10
4    2025-01-25
Name: data_venda, dtype: str

In [24]:
## Tentativa de conversão sem alterar a coluna original
datas_convertidas = pd.to_datetime(df_vendas['data_venda'], format='mixed', errors='coerce', dayfirst=True)
print(f'DATAS QUE NÃO PUDERAM SER INTERPRETADAS: {datas_convertidas.isna().sum()}')

DATAS QUE NÃO PUDERAM SER INTERPRETADAS: 0

In [31]:
# VERIFICAÇÃO DA PADRONIZAÇÃO DE STATUS, CATEGORIAS E CANAIS

print('VALORES ENCONTRADOS EM STATUS')
display(df_vendas['status'].value_counts(dropna=False))
print('\nVALORES ENCONTRADOS EM CATEGORIAS')
display(df_produtos['categoria'].value_counts(dropna=False))
print('\nVALORES ENCONTRADOS EM CANAIS')
display(df_vendas['canal_venda'].value_counts(dropna=False))

VALORES ENCONTRADOS EM STATUS

status
Concluída    9322
Cancelada     469
Devolvida     211
CANCELADA       5
concluida       5
Name: count, dtype: int64

VALORES ENCONTRADOS EM CATEGORIAS

categoria
Informática         7
Eletrodomésticos    5
Eletrônicos         4
Escritório          3
Eletronicos         1
Name: count, dtype: int64

VALORES ENCONTRADOS EM CANAIS

canal_venda
E-commerce     3757
Loja Física    3024
Marketplace    2211
Televendas     1010
NaN              10
Name: count, dtype: int64